### ISSUE TITLE
Is it possible to install Open Assistant on Raspberry Pi?

### ISSUE THREAD

**Issue by ChronoSynth** [openassistant/oa-core#13]
Hi. I want to run Open Assistant on Raspberry Pi, but I'm having trouble installing the dependencies. The website says nothing about installing OA onto Raspberry Pi. Is it possible, and how can my issue be fixed?

**Comment by joshuashort** [comment]
Yes, it should be possible. If your RasPi's OS has Python3 and all the dependencies, you're good to go. Worst case scenario, you'll have to manually fetch/compile some dependencies.

What're you having trouble with?

**Comment by ChronoSynth** [comment]
I was originally having trouble installing the dependencies using `pip install -r requirements.txt`, but after reflashing my SD card, I installed almost all of the dependencies using `pip3 install keyboard sounddevice playsound requests pyttsx3 psutil feedparser python-forecastio numpy`. (I've decided to use DeepSpeech for speech recognition) Do the dependencies need to be in a certain place?

**Comment by joshuashort** [comment]
There are system-level dependencies and some Python ones. If you're using Raspbian, it's going to be similar to [installing on Ubuntu](https://github.com/openassistant/oa-core/wiki/Installation#ubuntu-linux). Things can vary by distro/repo, so you might need to add a "3" to some of the python package names.

They just need to be where they're supposed to be.. generally, `pip` and `apt` take care of that. Depends on the environment.

I'm going to close this issue since it is possible to install. Open another issue if there's something that needs to be addressed?

(to switch from pocketsphinx to DeepSpeech, look into the `speech_recognition` module; it might take changes to `ear` as well)
