### ISSUE TITLE
Does not work on Linux

### ISSUE THREAD

**Issue by thanos-the-tank-engine** [openassistant/oa-core#42]
**Describe the bug**
The software starts up and then does nothing but throw an error
**To Reproduce**
Start the software

**Comment by ghost** [comment]
It would help if there were more details (what flavor of Linux? What hardware? What's the specific error?), but...

There are a few complaints OA will make if it doesn't recognize hardware: the first is a flood of errors that spits out the minute you start the program and runs on infinite loop. You'll notice they make mention of "ear" -- that's your clue that the software isn't detecting your _input_ hardware. Are you able to record anything on the system? Is there any specific error that "ear" is generating? 

If you aren't seeing any errors on boot, that's a good sign! Next try saying the "Boot Mind" command. If you don't get an error, but also don't hear any output, first verify you can play sound in another context. 

It is also a possibility that you can play sound in general, but not with Python. Something else to double-check.

Lastly, you may be using a device that has an "audio" and "video" group  You may need to use usermod to add yourself to the appropriate group(s) (if you can)  Again, _**verify you can record and play sound in general with the system you're testing on, and with the version of python you're using.**_

I encountered some issues running via SSH that were due to the user groups above. Try running directly on-device first as a verification step.

Lastly I've [left some tips on dealing with ALSA and Raspberry Pi OS issues specifically here](https://github.com/openassistant/oa-core/issues/45). If that fits your use case, check it out.

Since this was first reported in January, I should also [point out this closed ticket](https://github.com/openassistant/oa-core/issues/43) which is now patched. It might be worth giving it another shot.
 
Hope this helps!

**Comment by thanos-the-tank-engine** [comment]
I'm sorry, this issue was due to a server outage and actually not Linux specific. I just forgot to close it
